### ISSUE TITLE
Font problem in dark mode

### ISSUE THREAD

**Issue by shaonianche** [YunYouJun/web-resume#1]
The contrast of font color in dark mode is not obvious, do you think?
![image](https://user-images.githubusercontent.com/16186646/123634709-5ed48700-d84d-11eb-859e-50c1a989fc07.png)

**Comment by YunYouJun** [comment]
Yeah. Thanks. This is a known issue, but due to time, the style will be optimized later.

**Comment by shaonianche** [comment]
> Yeah. Thanks. This is a known issue, but due to time, the style will be optimized later.
Aha, got it, maybe I can try to improve it (before you have time to modify it)

**Comment by YunYouJun** [comment]
Hey, this problem has be fixed in https://github.com/YunYouJun/web-resume/commit/afece98f9b97560b5ed76d815665489760fcf21a.

![image](https://user-images.githubusercontent.com/25154432/125167273-457af580-e1d2-11eb-95df-a210fe745ff1.png)

Any other suggestions are welcome.
Have Fun!
