### ISSUE TITLE
请问大佬怎样才能把浏览器中的自己的简历的 yaml 数据清除 ？

### ISSUE THREAD

**Issue by Brannua** [YunYouJun/web-resume#7]
- 因为 yaml 格式写错了，导致浏览器一旦打开简历编辑器就会导致电脑风扇狂转，浏览器崩溃

- 所以想问问怎么清除掉自己浏览器上缓存的 yaml ？

**Comment by YunYouJun** [comment]
<img width="1329" alt="image" src="https://user-images.githubusercontent.com/25154432/157175235-41d0f053-6e1f-4b98-8e18-52dd437c5a95.png">

打开控制台，删除该字段即可。

**Comment by YunYouJun** [comment]
是否有错误原因及示例，我争取适配下。

**Comment by Brannua** [comment]
谢谢大佬，这两天不知道咋回事我的网络代理失效了github上不去，经过测试，大致情况就是 yaml 的内容一旦有语法错误或者填入不是 yaml 文本的其他任意字符，都会导致当前网页完全卡死，笔记本电脑风扇会狂转，进而网页崩溃，没有例外。。



 发自我的企业微信     
 
 &nbsp;


 ----------回复的邮件信息----------
 ***@***.***&gt; 于2022年3月8日(周二) 中午1:55写道:

  

 
是否有错误原因及示例，我争取适配下。

**Comment by Brannua** [comment]
> 是否有错误原因及示例，我争取适配下。

大佬我又翻出来了，是这样的，我本想直接将写好的 yaml 复制粘贴到您的在线简历编辑器中，但是由于粘贴内容的时候，内容含有语法错误，导致刚粘进去页面就瞬间卡死了，紧接着风扇呼呼转，我甚至无法清除 localStorage，即使关掉浏览器注销或关机重启再次进入简历编辑网页都是一旦进入就立即卡死，根本没机会清除 localStorage（打开控制台点击 clear 没反应，console 中执行脚本回车都按不动），不知道该咋办了

**Comment by YunYouJun** [comment]
对了，既然你直接本地写 YAML，你可以 clone 项目直接在本地写。访问 `localhost:xxxx/local` 即可。

在线编辑器这个问题我最近看看修一下。（~~影响使用，深感抱歉~~）

**Comment by Brannua** [comment]
> 对了，既然你直接本地写 YAML，你可以 clone 项目直接在本地写。访问 `localhost:xxxx/local` 即可。
> 
> 在线编辑器这个问题我最近看看修一下。（~影响使用，深感抱歉~）

对奥哈哈，忘了拉本地用了，谢谢大佬 ！

**Comment by YunYouJun** [comment]
这是 monaco-yaml 与 vite 导致的一个 BUG，通过非常魔法的方式解决了。同时这也修复了在线的类型验证。

https://github.com/remcohaszing/monaco-yaml/issues/150

More info see https://github.com/YunYouJun/web-resume/commit/6a406504a1b5a1373d88db2fec7bd14ecaaee268 https://github.com/YunYouJun/web-resume/commit/381fea0238a1254649e22f39b5372dea2e768f76.

**Comment by Brannua** [comment]
谢谢大佬，但是这个 bug 我这边测试还有问题，你试试在编辑器中光标定位在任意一行，然后使用 alt+上下方向键 的方式不断改变行的位置，在调整行位置的过程中，一旦遇上语法错误，基本上当前网页就会卡死崩溃；另外，我尝试清空了 localStorage，发现在编辑器内 yaml 编辑区域如果没有任何字符，没有任何文本内容，页面也会卡死

**Comment by Brannua** [comment]
https://user-images.githubusercontent.com/38487617/158044736-4ba99443-97cd-4c37-8885-3490572c278c.mp4

**Comment by Brannua** [comment]
https://user-images.githubusercontent.com/38487617/158044808-09b680d9-d2cb-4305-b3a6-8e7868bbf979.mp4

**Comment by YunYouJun** [comment]
我添加了 ajv 来预先检验 yml 生成的 json 是否符合规范，来避免传入的数据导致卡死。
当格式错误时，将不会显示简历预览内容。
我认为现在已经真正可以解决目前的问题。当然如果本地使用，也更加方便快捷。
