### ISSUE TITLE
打印 pdf 链接失效问题

### ISSUE THREAD

**Issue by Ghjk94522** [YunYouJun/web-resume#8]
如题，按照 readme 里面的操作使用：右键-打印-保存为 pdf 后，不能使用简历中的链接，亦不能选择文字（看起来是简历直接变成一张 pdf 格式的图片了，请问有无解决办法？

（我用的是 edge，不清楚 chrome 是否存在这一问题）

**Comment by YunYouJun** [comment]
Chrome 导出 PDF 后保留链接。

我的示例：

[Web Resume.pdf](https://github.com/YunYouJun/web-resume/files/9072350/Web.Resume.pdf)
